export const layoutOrder = ["xfull", "full", "tkl", "60"]

export const miniKeyClassMap = {
   "CtrlRight": "w1_25_",
}

export default {
   "xfull": {
      displayName: "X-Full-size",
      layout: [
         [ // 1
            { empty: true, width: "w1" },
            { spacer: true },
            { id: "Esc", label: "Esc", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F1", label: "F1", width: "w1" },
            { id: "F2", label: "F2", width: "w1" },
            { id: "F3", label: "F3", width: "w1" },
            { id: "F4", label: "F4", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F5", label: "F5", width: "w1" },
            { id: "F6", label: "F6", width: "w1" },
            { id: "F7", label: "F7", width: "w1" },
            { id: "F8", label: "F8", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F9", label: "F9", width: "w1" },
            { id: "F10", label: "F10", width: "w1" },
            { id: "F11", label: "F11", width: "w1" },
            { id: "F12", label: "F12", width: "w1" },
            { spacer: true },
            { id: "PrtSc", label: "PrtSc", width: "w1" },
            { id: "Scroll", label: "ScrLk", width: "w1" },
            { id: "Pause", label: "Pause", width: "w1" },
            { spacer: true },
         ],
         [ // 2
            { id: "Extra1", label: "G1", width: "w1" },
            { spacer: true },
            { id: "Backtick", label: "`", width: "w1" },
            { id: "Digit1", label: "1", width: "w1" },
            { id: "Digit2", label: "2", width: "w1" },
            { id: "Digit3", label: "3", width: "w1" },
            { id: "Digit4", label: "4", width: "w1" },
            { id: "Digit5", label: "5", width: "w1" },
            { id: "Digit6", label: "6", width: "w1" },
            { id: "Digit7", label: "7", width: "w1" },
            { id: "Digit8", label: "8", width: "w1" },
            { id: "Digit9", label: "9", width: "w1" },
            { id: "Digit0", label: "0", width: "w1" },
            { id: "Minus", label: "-", width: "w1" },
            { id: "Equal", label: "=", width: "w1" },
            { id: "Backspace", label: "Backspace", width: "w2_" },
            { spacer: true },
            { id: "Insert", label: "Ins", width: "w1" },
            { id: "Home", label: "Home", width: "w1" },
            { id: "PageUp", label: "PgUp", width: "w1" },
            { spacer: true },
            { id: "NumLock", label: "Num", width: "w1" },
            { id: "NumpadDivide", label: "/", width: "w1" },
            { id: "NumpadMultiply", label: "*", width: "w1" },
            { id: "NumpadSubtract", label: "-", width: "w1" },
         ],
         [ // 3
            { id: "Extra2", label: "G2", width: "w1" },
            { spacer: true },
            { id: "Tab", label: "Tab", width: "w1_5_" },
            { id: "KeyQ", label: "Q", width: "w1" },
            { id: "KeyW", label: "W", width: "w1" },
            { id: "KeyE", label: "E", width: "w1" },
            { id: "KeyR", label: "R", width: "w1" },
            { id: "KeyT", label: "T", width: "w1" },
            { id: "KeyY", label: "Y", width: "w1" },
            { id: "KeyU", label: "U", width: "w1" },
            { id: "KeyI", label: "I", width: "w1" },
            { id: "KeyO", label: "O", width: "w1" },
            { id: "KeyP", label: "P", width: "w1" },
            { id: "KeyŠ", label: "Š", width: "w1" },
            { id: "KeyĐ", label: "Đ", width: "w1" },
            { id: "Enter", label: "Enter", width: "w1_5" },
            { spacer: true },
            { id: "Delete", label: "Del", width: "w1" },
            { id: "End", label: "End", width: "w1" },
            { id: "PageDown", label: "PgDn", width: "w1" },
            { spacer: true },
            { id: "Numpad7", label: "7", width: "w1" },
            { id: "Numpad8", label: "8", width: "w1" },
            { id: "Numpad9", label: "9", width: "w1" },
            { id: "NumpadAdd", label: "+", width: "w1" },
         ],
         [ // 4
            { id: "Extra3", label: "G3", width: "w1" },
            { spacer: true },
            { id: "CapsLock", label: "Caps", width: "w1_75_" },
            { id: "KeyA", label: "A", width: "w1" },
            { id: "KeyS", label: "S", width: "w1" },
            { id: "KeyD", label: "D", width: "w1" },
            { id: "KeyF", label: "F", width: "w1" },
            { id: "KeyG", label: "G", width: "w1" },
            { id: "KeyH", label: "H", width: "w1" },
            { id: "KeyJ", label: "J", width: "w1" },
            { id: "KeyK", label: "K", width: "w1" },
            { id: "KeyL", label: "L", width: "w1" },
            { id: "KeyČ", label: "Č", width: "w1" },
            { id: "KeyĆ", label: "Ć", width: "w1" },
            { id: "KeyŽ", label: "Ž", width: "w1" },
            { id: "Enter", label: "", width: "w1_25" },
            { spacer: true },
            { empty: true, width: "w1" },
            { empty: true, width: "w1" },
            { empty: true, width: "w1" },
            { spacer: true },
            { id: "Numpad4", label: "4", width: "w1" },
            { id: "Numpad5", label: "5", width: "w1" },
            { id: "Numpad6", label: "6", width: "w1" },
            { id: "NumpadAdd", label: "", width: "w1" },
         ],
         [ // 5
            { id: "Extra4", label: "G4", width: "w1" },
            { spacer: true },
            { id: "ShiftLeft", label: "Shift", width: "w2_25_" },
            { id: "KeyZ", label: "Z", width: "w1" },
            { id: "KeyX", label: "X", width: "w1" },
            { id: "KeyC", label: "C", width: "w1" },
            { id: "KeyV", label: "V", width: "w1" },
            { id: "KeyB", label: "B", width: "w1" },
            { id: "KeyN", label: "N", width: "w1" },
            { id: "KeyM", label: "M", width: "w1" },
            { id: "Comma", label: ",", width: "w1" },
            { id: "Period", label: ".", width: "w1" },
            { id: "Slash", label: "/", width: "w1" },
            { id: "ShiftRight", label: "Shift", width: "w3" },
            { spacer: true },
            { empty: true, width: "w1" },
            { id: "ArrowUp", label: "Up", width: "w1" },
            { empty: true, width: "w1" },
            { spacer: true },
            { id: "Numpad1", label: "1", width: "w1" },
            { id: "Numpad2", label: "2", width: "w1" },
            { id: "Numpad3", label: "3", width: "w1" },
            { id: "NumpadEnter", label: "Enter", width: "w1" },
         ],
         [ // 6
            { id: "Extra5", label: "G5", width: "w1" },
            { spacer: true },
            { id: "CtrlLeft", label: "Ctrl", width: "w1_25_" },
            { id: "MetaLeft", label: "Win", width: "w1_25_" },
            { id: "AltLeft", label: "Alt", width: "w1_25_" },
            { id: "Space", label: "Space", width: "w6_" },
            { id: "AltRight", label: "Alt", width: "w1_25_" },
            { id: "MetaRight", label: "Win", width: "w1_25_" },
            { id: "Menu", label: "Menu", width: "w1_25_" },
            { id: "CtrlRight", label: "Ctrl", width: "w1_5" },
            { spacer: true },
            { id: "ArrowLeft", label: "Left", width: "w1" },
            { id: "ArrowDown", label: "Down", width: "w1" },
            { id: "ArrowRight", label: "Right", width: "w1" },
            { spacer: true },
            { id: "Numpad0", label: "0", width: "w2_" },
            { id: "NumpadDecimal", label: ".", width: "w1" },
            { id: "NumpadEnter", label: "", width: "w1" },
         ],
      ],
   },
   "full": {
      displayName: "Full-size",
      layout: [
         [ // 1
            { id: "Esc", label: "Esc", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F1", label: "F1", width: "w1" },
            { id: "F2", label: "F2", width: "w1" },
            { id: "F3", label: "F3", width: "w1" },
            { id: "F4", label: "F4", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F5", label: "F5", width: "w1" },
            { id: "F6", label: "F6", width: "w1" },
            { id: "F7", label: "F7", width: "w1" },
            { id: "F8", label: "F8", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F9", label: "F9", width: "w1" },
            { id: "F10", label: "F10", width: "w1" },
            { id: "F11", label: "F11", width: "w1" },
            { id: "F12", label: "F12", width: "w1" },
            { spacer: true },
            { id: "PrtSc", label: "PrtSc", width: "w1" },
            { id: "Scroll", label: "ScrLk", width: "w1" },
            { id: "Pause", label: "Pause", width: "w1" },
         ],
         [ // 2
            { id: "Backtick", label: "`", width: "w1" },
            { id: "Digit1", label: "1", width: "w1" },
            { id: "Digit2", label: "2", width: "w1" },
            { id: "Digit3", label: "3", width: "w1" },
            { id: "Digit4", label: "4", width: "w1" },
            { id: "Digit5", label: "5", width: "w1" },
            { id: "Digit6", label: "6", width: "w1" },
            { id: "Digit7", label: "7", width: "w1" },
            { id: "Digit8", label: "8", width: "w1" },
            { id: "Digit9", label: "9", width: "w1" },
            { id: "Digit0", label: "0", width: "w1" },
            { id: "Minus", label: "-", width: "w1" },
            { id: "Equal", label: "=", width: "w1" },
            { id: "Backspace", label: "Backspace", width: "w2_" },
            { spacer: true },
            { id: "Insert", label: "Ins", width: "w1" },
            { id: "Home", label: "Home", width: "w1" },
            { id: "PageUp", label: "PgUp", width: "w1" },
            { spacer: true },
            { id: "NumLock", label: "Num", width: "w1" },
            { id: "NumpadDivide", label: "/", width: "w1" },
            { id: "NumpadMultiply", label: "*", width: "w1" },
            { id: "NumpadSubtract", label: "-", width: "w1" },
         ],
         [ // 3
            { id: "Tab", label: "Tab", width: "w1_5_" },
            { id: "KeyQ", label: "Q", width: "w1" },
            { id: "KeyW", label: "W", width: "w1" },
            { id: "KeyE", label: "E", width: "w1" },
            { id: "KeyR", label: "R", width: "w1" },
            { id: "KeyT", label: "T", width: "w1" },
            { id: "KeyY", label: "Y", width: "w1" },
            { id: "KeyU", label: "U", width: "w1" },
            { id: "KeyI", label: "I", width: "w1" },
            { id: "KeyO", label: "O", width: "w1" },
            { id: "KeyP", label: "P", width: "w1" },
            { id: "KeyŠ", label: "Š", width: "w1" },
            { id: "KeyĐ", label: "Đ", width: "w1" },
            { id: "Enter", label: "Enter", width: "w1_5" },
            { spacer: true },
            { id: "Delete", label: "Del", width: "w1" },
            { id: "End", label: "End", width: "w1" },
            { id: "PageDown", label: "PgDn", width: "w1" },
            { spacer: true },
            { id: "Numpad7", label: "7", width: "w1" },
            { id: "Numpad8", label: "8", width: "w1" },
            { id: "Numpad9", label: "9", width: "w1" },
            { id: "NumpadAdd", label: "+", width: "w1" },
         ],
         [ // 4
            { id: "CapsLock", label: "Caps", width: "w1_75_" },
            { id: "KeyA", label: "A", width: "w1" },
            { id: "KeyS", label: "S", width: "w1" },
            { id: "KeyD", label: "D", width: "w1" },
            { id: "KeyF", label: "F", width: "w1" },
            { id: "KeyG", label: "G", width: "w1" },
            { id: "KeyH", label: "H", width: "w1" },
            { id: "KeyJ", label: "J", width: "w1" },
            { id: "KeyK", label: "K", width: "w1" },
            { id: "KeyL", label: "L", width: "w1" },
            { id: "KeyČ", label: "Č", width: "w1" },
            { id: "KeyĆ", label: "Ć", width: "w1" },
            { id: "KeyŽ", label: "Ž", width: "w1" },
            { id: "Enter", label: "", width: "w1_25" },
            { spacer: true },
            { empty: true, width: "w1" },
            { empty: true, width: "w1" },
            { empty: true, width: "w1" },
            { spacer: true },
            { id: "Numpad4", label: "4", width: "w1" },
            { id: "Numpad5", label: "5", width: "w1" },
            { id: "Numpad6", label: "6", width: "w1" },
            { id: "NumpadAdd", label: "", width: "w1" },
         ],
         [ // 5
            { id: "ShiftLeft", label: "Shift", width: "w2_25_" },
            { id: "KeyZ", label: "Z", width: "w1" },
            { id: "KeyX", label: "X", width: "w1" },
            { id: "KeyC", label: "C", width: "w1" },
            { id: "KeyV", label: "V", width: "w1" },
            { id: "KeyB", label: "B", width: "w1" },
            { id: "KeyN", label: "N", width: "w1" },
            { id: "KeyM", label: "M", width: "w1" },
            { id: "Comma", label: ",", width: "w1" },
            { id: "Period", label: ".", width: "w1" },
            { id: "Slash", label: "/", width: "w1" },
            { id: "ShiftRight", label: "Shift", width: "w3" },
            { spacer: true },
            { empty: true, width: "w1" },
            { id: "ArrowUp", label: "Up", width: "w1" },
            { empty: true, width: "w1" },
            { spacer: true },
            { id: "Numpad1", label: "1", width: "w1" },
            { id: "Numpad2", label: "2", width: "w1" },
            { id: "Numpad3", label: "3", width: "w1" },
            { id: "NumpadEnter", label: "Enter", width: "w1" },
         ],
         [ // 6
            { id: "CtrlLeft", label: "Ctrl", width: "w1_25_" },
            { id: "MetaLeft", label: "Win", width: "w1_25_" },
            { id: "AltLeft", label: "Alt", width: "w1_25_" },
            { id: "Space", label: "Space", width: "w6_" },
            { id: "AltRight", label: "Alt", width: "w1_25_" },
            { id: "MetaRight", label: "Win", width: "w1_25_" },
            { id: "Menu", label: "Menu", width: "w1_25_" },
            { id: "CtrlRight", label: "Ctrl", width: "w1_5" },
            { spacer: true },
            { id: "ArrowLeft", label: "Left", width: "w1" },
            { id: "ArrowDown", label: "Down", width: "w1" },
            { id: "ArrowRight", label: "Right", width: "w1" },
            { spacer: true },
            { id: "Numpad0", label: "0", width: "w2_" },
            { id: "NumpadDecimal", label: ".", width: "w1" },
            { id: "NumpadEnter", label: "", width: "w1" },
         ],
      ],
   },
   "tkl": {
      displayName: "TKL",
      layout: [
         [ // 1
            { id: "Esc", label: "Esc", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F1", label: "F1", width: "w1" },
            { id: "F2", label: "F2", width: "w1" },
            { id: "F3", label: "F3", width: "w1" },
            { id: "F4", label: "F4", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F5", label: "F5", width: "w1" },
            { id: "F6", label: "F6", width: "w1" },
            { id: "F7", label: "F7", width: "w1" },
            { id: "F8", label: "F8", width: "w1" },
            { spacer: true },
            { spacer: true },
            { id: "F9", label: "F9", width: "w1" },
            { id: "F10", label: "F10", width: "w1" },
            { id: "F11", label: "F11", width: "w1" },
            { id: "F12", label: "F12", width: "w1" },
            { spacer: true },
            { id: "PrtSc", label: "PrtSc", width: "w1" },
            { id: "Scroll", label: "ScrLk", width: "w1" },
            { id: "Pause", label: "Pause", width: "w1" },
         ],
         [ // 2
            { id: "Backtick", label: "`", width: "w1" },
            { id: "Digit1", label: "1", width: "w1" },
            { id: "Digit2", label: "2", width: "w1" },
            { id: "Digit3", label: "3", width: "w1" },
            { id: "Digit4", label: "4", width: "w1" },
            { id: "Digit5", label: "5", width: "w1" },
            { id: "Digit6", label: "6", width: "w1" },
            { id: "Digit7", label: "7", width: "w1" },
            { id: "Digit8", label: "8", width: "w1" },
            { id: "Digit9", label: "9", width: "w1" },
            { id: "Digit0", label: "0", width: "w1" },
            { id: "Minus", label: "-", width: "w1" },
            { id: "Equal", label: "=", width: "w1" },
            { id: "Backspace", label: "Backspace", width: "w2_" },
            { spacer: true },
            { id: "Insert", label: "Ins", width: "w1" },
            { id: "Home", label: "Home", width: "w1" },
            { id: "PageUp", label: "PgUp", width: "w1" },
         ],
         [ // 3
            { id: "Tab", label: "Tab", width: "w1_5_" },
            { id: "KeyQ", label: "Q", width: "w1" },
            { id: "KeyW", label: "W", width: "w1" },
            { id: "KeyE", label: "E", width: "w1" },
            { id: "KeyR", label: "R", width: "w1" },
            { id: "KeyT", label: "T", width: "w1" },
            { id: "KeyY", label: "Y", width: "w1" },
            { id: "KeyU", label: "U", width: "w1" },
            { id: "KeyI", label: "I", width: "w1" },
            { id: "KeyO", label: "O", width: "w1" },
            { id: "KeyP", label: "P", width: "w1" },
            { id: "KeyŠ", label: "Š", width: "w1" },
            { id: "KeyĐ", label: "Đ", width: "w1" },
            { id: "Enter", label: "Enter", width: "w1_5" },
            { spacer: true },
            { id: "Delete", label: "Del", width: "w1" },
            { id: "End", label: "End", width: "w1" },
            { id: "PageDown", label: "PgDn", width: "w1" },
         ],
         [ // 4
            { id: "CapsLock", label: "Caps", width: "w1_75_" },
            { id: "KeyA", label: "A", width: "w1" },
            { id: "KeyS", label: "S", width: "w1" },
            { id: "KeyD", label: "D", width: "w1" },
            { id: "KeyF", label: "F", width: "w1" },
            { id: "KeyG", label: "G", width: "w1" },
            { id: "KeyH", label: "H", width: "w1" },
            { id: "KeyJ", label: "J", width: "w1" },
            { id: "KeyK", label: "K", width: "w1" },
            { id: "KeyL", label: "L", width: "w1" },
            { id: "KeyČ", label: "Č", width: "w1" },
            { id: "KeyĆ", label: "Ć", width: "w1" },
            { id: "KeyŽ", label: "Ž", width: "w1" },
            { id: "Enter", label: "", width: "w1_25" },
            { spacer: true },
            { empty: true, width: "w1" },
            { empty: true, width: "w1" },
            { empty: true, width: "w1" },
         ],
         [ // 5
            { id: "ShiftLeft", label: "Shift", width: "w2_25_" },
            { id: "KeyZ", label: "Z", width: "w1" },
            { id: "KeyX", label: "X", width: "w1" },
            { id: "KeyC", label: "C", width: "w1" },
            { id: "KeyV", label: "V", width: "w1" },
            { id: "KeyB", label: "B", width: "w1" },
            { id: "KeyN", label: "N", width: "w1" },
            { id: "KeyM", label: "M", width: "w1" },
            { id: "Comma", label: ",", width: "w1" },
            { id: "Period", label: ".", width: "w1" },
            { id: "Slash", label: "-", width: "w1" },
            { id: "ShiftRight", label: "Shift", width: "w3" },
            { spacer: true },
            { empty: true, width: "w1" },
            { id: "ArrowUp", label: "Up", width: "w1" },
         ],
         [ // 6
            { id: "CtrlLeft", label: "Ctrl", width: "w1_25_" },
            { id: "MetaLeft", label: "Win", width: "w1_25_" },
            { id: "AltLeft", label: "Alt", width: "w1_25_" },
            { id: "Space", label: "Space", width: "w6_" },
            { id: "AltRight", label: "Alt", width: "w1_25_" },
            { id: "MetaRight", label: "Win", width: "w1_25_" },
            { id: "Menu", label: "Menu", width: "w1_25_" },
            { id: "CtrlRight", label: "Ctrl", width: "w1_5" },
            { spacer: true },
            { id: "ArrowLeft", label: "Left", width: "w1" },
            { id: "ArrowDown", label: "Down", width: "w1" },
            { id: "ArrowRight", label: "Right", width: "w1" },
         ],
      ],
   },
   "60": {
      displayName: "60%",
      layout: [
         [ // 1
            { id: "Backtick", label: "`", width: "w1" },
            { id: "Digit1", label: "1", width: "w1" },
            { id: "Digit2", label: "2", width: "w1" },
            { id: "Digit3", label: "3", width: "w1" },
            { id: "Digit4", label: "4", width: "w1" },
            { id: "Digit5", label: "5", width: "w1" },
            { id: "Digit6", label: "6", width: "w1" },
            { id: "Digit7", label: "7", width: "w1" },
            { id: "Digit8", label: "8", width: "w1" },
            { id: "Digit9", label: "9", width: "w1" },
            { id: "Digit0", label: "0", width: "w1" },
            { id: "Minus", label: "-", width: "w1" },
            { id: "Equal", label: "=", width: "w1" },
            { id: "Backspace", label: "Backspace", width: "w2_" },
         ],
         [ // 2
            { id: "Tab", label: "Tab", width: "w1_5_" },
            { id: "KeyQ", label: "Q", width: "w1" },
            { id: "KeyW", label: "W", width: "w1" },
            { id: "KeyE", label: "E", width: "w1" },
            { id: "KeyR", label: "R", width: "w1" },
            { id: "KeyT", label: "T", width: "w1" },
            { id: "KeyY", label: "Y", width: "w1" },
            { id: "KeyU", label: "U", width: "w1" },
            { id: "KeyI", label: "I", width: "w1" },
            { id: "KeyO", label: "O", width: "w1" },
            { id: "KeyP", label: "P", width: "w1" },
            { id: "KeyŠ", label: "Š", width: "w1" },
            { id: "KeyĐ", label: "Đ", width: "w1" },
            { id: "Enter", label: "Enter", width: "w1_5" },
         ],
         [ // 3
            { id: "CapsLock", label: "Caps", width: "w1_75_" },
            { id: "KeyA", label: "A", width: "w1" },
            { id: "KeyS", label: "S", width: "w1" },
            { id: "KeyD", label: "D", width: "w1" },
            { id: "KeyF", label: "F", width: "w1" },
            { id: "KeyG", label: "G", width: "w1" },
            { id: "KeyH", label: "H", width: "w1" },
            { id: "KeyJ", label: "J", width: "w1" },
            { id: "KeyK", label: "K", width: "w1" },
            { id: "KeyL", label: "L", width: "w1" },
            { id: "KeyČ", label: "Č", width: "w1" },
            { id: "KeyĆ", label: "Ć", width: "w1" },
            { id: "KeyŽ", label: "Ž", width: "w1" },
            { id: "Enter", label: "", width: "w1_25" },
         ],
         [ // 4
            { id: "ShiftLeft", label: "Shift", width: "w2_25_" },
            { id: "KeyZ", label: "Z", width: "w1" },
            { id: "KeyX", label: "X", width: "w1" },
            { id: "KeyC", label: "C", width: "w1" },
            { id: "KeyV", label: "V", width: "w1" },
            { id: "KeyB", label: "B", width: "w1" },
            { id: "KeyN", label: "N", width: "w1" },
            { id: "KeyM", label: "M", width: "w1" },
            { id: "Comma", label: ",", width: "w1" },
            { id: "Period", label: ".", width: "w1" },
            { id: "Slash", label: "/", width: "w1" },
            { id: "ShiftRight", label: "Shift", width: "w3" },
         ],
         [ // 5
            { id: "CtrlLeft", label: "Ctrl", width: "w1_25_" },
            { id: "MetaLeft", label: "Win", width: "w1_25_" },
            { id: "AltLeft", label: "Alt", width: "w1_25_" },
            { id: "Space", label: "Space", width: "w6_" },
            { id: "AltRight", label: "Alt", width: "w1_25_" },
            { id: "MetaRight", label: "Win", width: "w1_25_" },
            { id: "Menu", label: "Menu", width: "w1_25_" },
            { id: "CtrlRight", label: "Ctrl", width: "w1_5" },
         ],
      ],
   }
}
